/* MOCK_MODE: 백엔드 미연결시 사용하는 mock 데이터. 제거하려면 이 파일과 orders-api.ts의 networkError 핸들링 부분을 함께 삭제 */
import type {
  ArchiveCompletedOrdersResponse,
  HideOrderResponse,
  KdsOrdersResponse,
  OrderItemProgressResponse,
  OrderStatus,
} from "../types";

const now = new Date();
const minutesAgo = (n: number) => new Date(now.getTime() - n * 60000).toISOString();

export const mockKdsOrdersResponse: KdsOrdersResponse = {
  orders: [
    {
      id: 1,
      platform: "YOGIYO",
      store_id: "MOCK-STORE-001",
      external_order_id: "EXT-001",
      order_number: "A001",
      status: "NEW",
      customer_request: "덜 맵게 해주세요",
      delivery_request: "문 앞에 놓아주세요",
      deliveryPhone: "01011112222",
      deliveryZipNo: "04524",
      deliveryRoadAddress: "서울시 중구 을지로 10",
      deliveryJibunAddress: "서울시 중구 을지로동 10",
      deliveryAddressDetail: "301호",
      ordered_at: minutesAgo(5),
      created_at: minutesAgo(5),
      updated_at: minutesAgo(5),
      hidden: false,
      hiddenAt: null,
      archived: false,
      archivedAt: null,
      items: [
        {
          id: 101,
          name: "김치찌개",
          quantity: 1,
          targetQuantity: 2,
          completedQuantity: 0,
          options: [],
          unit_price: 8000,
          total_price: 8000,
          done: false,
          doneAt: null,
          doneByUserId: null,
        },
        {
          id: 102,
          name: "제육볶음",
          quantity: 2,
          targetQuantity: 4,
          completedQuantity: 0,
          options: [
            {
              id: "opt-101-1",
              parentItemId: 102,
              label: "곱빼기",
              groupName: "옵션",
              optionName: "곱빼기",
              sortOrder: 0,
              targetQuantity: 2,
              completedQuantity: 0,
              done: false,
              doneAt: null,
              doneByUserId: null,
            },
          ],
          unit_price: 9000,
          total_price: 18000,
          done: false,
          doneAt: null,
          doneByUserId: null,
        },
      ],
      aiAnalysis: {
        summary: "고객 요청사항 확인 필요",
        tags: ["덜맵게"],
        cookingNotes: ["덜 맵게 조리"],
        packingNotes: [],
        deliveryNotes: ["문 앞에 놓아주세요"],
        kitchenActions: [],
        packingActions: [],
        ignoredRequests: [],
        riskLevel: "LOW",
        warnings: [],
        needsHumanCheck: false,
        analysisStatus: "COMPLETED",
      },
    },
    {
      id: 2,
      platform: "BAEMIN",
      store_id: "MOCK-STORE-001",
      external_order_id: "EXT-002",
      order_number: "A002",
      status: "COOKING",
      customer_request: null,
      delivery_request: null,
      deliveryPhone: "01033334444",
      deliveryZipNo: null,
      deliveryRoadAddress: null,
      deliveryJibunAddress: null,
      deliveryAddressDetail: null,
      ordered_at: minutesAgo(15),
      created_at: minutesAgo(15),
      updated_at: minutesAgo(10),
      hidden: false,
      hiddenAt: null,
      archived: false,
      archivedAt: null,
      items: [
        {
          id: 201,
          name: "된장찌개",
          quantity: 1,
          targetQuantity: 2,
          completedQuantity: 1,
          options: [],
          unit_price: 7000,
          total_price: 7000,
          done: false,
          doneAt: null,
          doneByUserId: null,
        },
        {
          id: 202,
          name: "불고기",
          quantity: 1,
          targetQuantity: 3,
          completedQuantity: 2,
          options: [
            {
              id: "opt-201-1",
              parentItemId: 202,
              label: "치즈추가",
              groupName: "추가",
              optionName: "치즈추가",
              sortOrder: 0,
              targetQuantity: 1,
              completedQuantity: 1,
              done: true,
              doneAt: minutesAgo(5),
              doneByUserId: 1,
            },
          ],
          unit_price: 12000,
          total_price: 12000,
          done: false,
          doneAt: null,
          doneByUserId: null,
        },
      ],
      aiAnalysis: null,
    },
    {
      id: 3,
      platform: "COUPANG_EATS",
      store_id: "MOCK-STORE-001",
      external_order_id: "EXT-003",
      order_number: "B001",
      status: "DONE",
      customer_request: "포장 부탁드려요",
      delivery_request: null,
      deliveryPhone: "01055556666",
      deliveryZipNo: "04524",
      deliveryRoadAddress: "서울시 중구 을지로 20",
      deliveryJibunAddress: "서울시 중구 을지로동 20",
      deliveryAddressDetail: null,
      ordered_at: minutesAgo(30),
      created_at: minutesAgo(30),
      updated_at: minutesAgo(5),
      hidden: false,
      hiddenAt: null,
      archived: false,
      archivedAt: null,
      items: [
        {
          id: 301,
          name: "비빔밥",
          quantity: 2,
          targetQuantity: 2,
          completedQuantity: 2,
          options: [],
          unit_price: 9000,
          total_price: 18000,
          done: true,
          doneAt: minutesAgo(5),
          doneByUserId: 1,
        },
      ],
      aiAnalysis: null,
    },
  ],
};

export const mockHideOrderResponse: HideOrderResponse = {
  orderId: 0,
  hidden: true,
};

export const mockArchiveCompletedOrdersResponse: ArchiveCompletedOrdersResponse = {
  archivedCount: 0,
};

export function mockOrderItemProgressResponse(
  orderItemId: number,
  payload: { done?: boolean; delta?: number; completedQuantity?: number },
  optionIndex: number | null = null,
): OrderItemProgressResponse {
  return {
    orderItemId,
    optionIndex,
    targetQuantity: 10,
    completedQuantity: payload.completedQuantity ?? payload.delta ?? 0,
    done: payload.done ?? false,
    doneAt: payload.done ? new Date().toISOString() : null,
    doneByUserId: payload.done ? 1 : null,
  };
}

export function mockUpdateOrderStatusResponse(
  orderId: number,
  status: OrderStatus,
): { id: number; status: OrderStatus } {
  return { id: orderId, status };
}
